### PR TITLE
chore: support aioswitcher 3.4.1

### PR DESCRIPTION
**Pull request by YogevBokobza**
## Description

> Describe what you did and why.

**Related issue (if any):** fixes #issue_number_goes_here

## Checklist

- [x] I have followed this repository's contributing guidelines.
- [x] I will adhere to the project's code of conduct.

## Additional information

> Anything else?

### CODE REVIEW

**Comment by TomerFi** [comment]
@YogevBokobza Thank you!
Do you know if this will work for devices without a key? i.e., Cases where we have not `request.query[KEY_LOGIN_KEY]`.

**Comment by YogevBokobza** [comment]
> @YogevBokobza Thank you! Do you know if this will work for devices without a key? i.e., Cases where we have not `request.query[KEY_LOGIN_KEY]`.

login key must be set. even if it's just 00

**Comment by TomerFi** [comment]
> login key must be set. even if it's just 00

This means this is a breaking change.

**Comment by YogevBokobza** [comment]
> > login key must be set. even if it's just 00
> 
> This means this is a breaking change.

Hmm.. Maybe I can question if request.query[KEY_LOGIN_KEY] is exists and if not then send "00" ?

**Comment by YogevBokobza** [comment]
> > login key must be set. even if it's just 00
> 
> This means this is a breaking change.

@TomerFi  Can you check this commit? (https://github.com/TomerFi/switcher_webapi/pull/705/commits/2872c0f04decd564bfe3741abb150c20a8e0453c)
Do you think it will work? I am not familiar with how to test this project.

**Comment by TomerFi** [comment]
> > > login key must be set. even if it's just 00
> > 
> > 
> > This means this is a breaking change.
> 
> @TomerFi Can you check this commit? ([2872c0f](https://github.com/TomerFi/switcher_webapi/commit/2872c0f04decd564bfe3741abb150c20a8e0453c)) Do you think it will work? I am not familiar with how to test this project.

LGTM

**Comment by YogevBokobza** [comment]
> > > > login key must be set. even if it's just 00
> > > 
> > > 
> > > This means this is a breaking change.
> > 
> > 
> > @TomerFi Can you check this commit? ([2872c0f](https://github.com/TomerFi/switcher_webapi/commit/2872c0f04decd564bfe3741abb150c20a8e0453c)) Do you think it will work? I am not familiar with how to test this project.
> 
> LGTM

So can we merge?

**Review by TomerFi — APPROVED** [review]

**Comment by TomerFi** [comment]
@allcontributors add @YogevBokobza for code, doc, test

**Comment by TomerFi** [comment]
Included in [1.2.5](https://github.com/TomerFi/switcher_webapi/releases/tag/1.2.5)

**Pull request merged**
