### PR TITLE
Removed excess " on docker run command

### PR DESCRIPTION
**Pull request by OrBin**
# Description
Just fixed a little typo.

### CODE REVIEW

**Comment by TomerFi** [comment]
@OrBin
thank you!
:-)

**Review by TomerFi — APPROVED** [review]

**Comment by OrBin** [comment]
@TomerFi can you help me figure out why the build checks failed? I can't see any output, just "This check failed" on the Checks tab.

**Comment by TomerFi** [comment]
I'm looking into it right now.
It says that an internal error occurred.
I'm trying to restart it...
I think I may have reached the runtime limit for my account,
if that's the case, then I guess everything will be ok by tomorrow.

**Comment by TomerFi** [comment]
It was a `GitHub` issue,
everything works fine now.

**Pull request merged**
